config/routes.rb
Rails.application.routes.draw do
  get "request/create"
  get "pages/home"
  get "pages/dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"

  get "home" => "pages#home", as: :home
  get "userdashboard" => "pages#user_dashboard", as: :user_dashboard
  get "globaldashboard" => "pages#global_dashboard", as: :global_dashboard
  get "/search_suggestions", to: "requests#search_suggestions"

  post "simulate_requests", to: "requests#simulate_requests", as: :simulate_requests

  delete "clear_requests", to: "requests#clear_requests", as: :clear_requests


  resources :requests, only: [ :create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :request_analytics, dependent: :destroy
end

app/models/request_analytic.rb
class RequestAnalytic < ApplicationRecord
  belongs_to :request
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def user_dashboard
    @ip = request.remote_ip
    @requests = Request.where(ip_adress: @ip)
    @requests_5days = Request.where(timestamp: 5.days.ago..Time.now).where(ip_adress: @ip)
    @top_requests = RequestAnalytic.where(request_id: @requests.pluck(:id)).order(count: :desc).limit(5)
  end

  def global_dashboard
    @requests = Request.all
    @requests_ips = @requests.to_a.group_by(&:ip_adress)
    @request_today = Request.where(timestamp: Date.today)
    @daily_average = Request.count / 30
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  protect_from_forgery with: :null_session
  def create
    @request = Request.create!(
      ip_adress: request.remote_ip,
      query: params[:query],
      timestamp: Time.now
    )


    tracked_request = Request.find_by(ip_adress: request.remote_ip, query: params[:query])

    save_request(tracked_request, @request)

    head :ok
  end

  def simulate_requests
    generate_fake_queries.each do |query|
        @request = Request.create!(
          ip_adress: request.remote_ip,
          query: generate_fake_queries.sample,
          timestamp: Faker::Time.between(from: 1.month.ago, to: Time.now)
        )

        tracked_request = Request.find_by(ip_adress: @request.ip_adress, query: @request.query)

        save_request(tracked_request, @request)
    end

    redirect_to user_dashboard_path
  end

  def clear_requests
    @requests = Request.where(ip_adress: request.remote_ip)
    @requests.destroy_all

    redirect_to user_dashboard_path
  end

  def search_suggestions
    query = params[:query].to_s.strip

    suggestions = Request
      .where("query ILIKE ?", "%#{query}%")
      .distinct
      .order(:query)
      .limit(5)
      .pluck(:query)

    render json: suggestions
  end


  private
  def generate_fake_queries
    prefix = [ "what is", "where to find", "reviews of" ]
    queries = []

    prefix.each do |p|
      10.times do
        queries << "#{p} #{Faker::Movie.title}"
        queries << "#{p} #{Faker::Book.title}"
        queries << "#{p} #{Faker::Music.band}"
      end
    end

    queries
  end

  def save_request(tracked_request, request)
    if tracked_request && tracked_request.id != request.id
      analytics = RequestAnalytic.find_or_initialize_by(request_id: tracked_request.id)
    else
      analytics = RequestAnalytic.find_or_initialize_by(request_id: request.id)
    end

    analytics.count ||= 0
    analytics.count += 1
    analytics.save!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Realtimesearch" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= javascript_include_tag 'search_logger' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/global_dashboard.html.erb
<div class="container my-4">
  <h1 class="fw-bold">Global Analytics:</h1>

  <div class="tabs row my-4 column-gap-4 mx-2" style="height: 250px;">
    <div class="col border border-success-subtle p-4 d-flex flex-column justify-content-center align-items-center">
      <h2 class="mb-2 fw-bold" style="color: green;" ><%= @requests.count %></h2>
      <p>total requests, coming from:</p>
      <h2 class="mb-2 fw-bold" style="color: green;" ><%= @requests_ips.count %></h2>
      <p>unique IPs</p>
    </div>

    <div class="col border border-success-subtle p-4 d-flex flex-column justify-content-center align-items-center">
      <% per = RequestAnalytic.count.to_f / Request.count * 100 %>
      <h2 class="mb-2 fw-bold" style="color: green;"><%= per.nan? ? 0 : per.round(2) %>%</h2>
      <p>are unique requests</p>
      <p><span class="fw-bold" style="color: green;"><%= RequestAnalytic.count %></span> out of <span class="fw-bold" style="color: green;"><%= Request.count %></span> </p>
    </div>

    <div class="col border border-success-subtle p-4 d-flex flex-column justify-content-center align-items-center">
      <h2 class="mb-2 fw-bold" style="color: green;"><%= @request_today.count %></h2>
      <p>requests were made today</p>

      <p ><%= @request_today.count > @daily_average ? "above" : "below" %> daily average <span class="fw-bold" style="color: green;">(<%= @daily_average %>)</span> </p>

    </div>
  </div>

  <div class="border border-success-subtle p-4 mx-2 my-4">
    <h3 class="fw-bold mb-4">daily requests graph:</h3>
    <%= line_chart Request.group_by_day(:timestamp).count, colors: ["#008000", "#666"] %>
  </div>

  <div class="border border-success-subtle p-4 mx-2 my-4">
    <h3 class="fw-bold mb-4">Top searches Overall:</h3>
     <%= bar_chart(RequestAnalytic.joins(:request).group('requests.query').order('SUM(request_analytics.count) DESC').limit(5).sum(:count), colors: ["#008000", "#666"]) %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="mx-auto p-2 mt-5" style="width: 600px; margin-top: 300px;">
  <div class="header mb-4 text-center">
    <h1 class="fw-bold my-2">Real-time Search</h1>
    <p>Press Enter to "search"</p>
  </div>

  <input type="text" id="search-input" placeholder="Search..." style="width: 100%;">
  <div id="last-word-message" style="margin-top: 5px; color: blue;" class="my-2"></div>
  <div id="search-message" style="margin-top: 10px; color: green;" class="my-2"></div>
</div>

app/views/pages/user_dashboard.html.erb
<div class="container my-4">
  <div class="d-flex justify-content-between">
    <h1 class="fw-bold">Your Analytics:</h1>

    <div class="d-flex">
      <%= button_to "Simulate Requests", simulate_requests_path, class: "btn btn-outline-success mx-2", method: :post, remote: true, form: { data: { turbo: false } } %>
      <%= button_to "Clear My Requests", clear_requests_path, class: "btn btn-outline-danger mx-2", method: :delete, remote: true, form: { data: { turbo: false } } %>
    </div>


  </div>

  <div class="tabs row my-4 column-gap-4" style="height: 250px;">
    <div class="col border border-primary-subtle p-4 d-flex flex-column justify-content-center align-items-center">
      <p class="mb-2">You have made</p>
      <h2 class="mb-2 fw-bold" style="color: blue;" ><%= @requests.count %></h2>
      <p>searches so far</p>
    </div>

    <div class="col border border-primary-subtle p-4 d-flex flex-column justify-content-center align-items-center">
      <p class="mb-2">You have made</p>
      <h2 class="mb-2 fw-bold" style="color: blue;"><%= @requests_5days.count %> Search</h2>
      <p>in the past 5 days</p>
    </div>

    <div class="col border border-primary-subtle p-4 d-flex flex-column justify-content-center align-items-center">
      <p class="mb-2">You searches count for</p>

      <% per = @requests.count.to_f / Request.count * 100 %>
      <h2 class="mb-2 fw-bold" style="color: blue;"> <%= per.nan? ? 0 : per.round(2) %>%</h2>
      <p>all searches so far</p>
    </div>

  </div>

  <div class="tabs row my-4 column-gap-4">
    <div class="col border border-primary-subtle p-4">
      <h3 class="mb-2 fw-bold">Your daily search graph:</h3>
      <%= line_chart(Request.where(ip_adress: @ip).group_by_day(:timestamp).count,colors: ["#03045e", "#666"]) %>
    </div>
  </div>

  <div class="tabs row my-4 column-gap-4 mb-4" style="height: 250px;">
    <div class="col border border-primary-subtle p-4">
      <h3 class="fw-bold mb-3">Your top searches:</h3>

      <ol>
        <%@top_requests.each do |request| %>
          <li class="mb-2">
            <span class="fw-bold"><%= request.request.query %></span>
            <span class="text-muted">(<%= request.count %> times)</span>
          </li>
        <% end %>
      </ol>
    </div>

    <div class="col border border-primary-subtle p-4">
      <h3 class="fw-bold mb-3">Your recent searches:</h3>

      <ol>
        <%@requests.order(created_at: :desc).limit(5).each do |request| %>
          <li class="mb-2">
            <span class="fw-bold"><%= request.query %></span>
            <span class="text-muted">on <%= request.timestamp %></span>
          </li>
        <% end %>
      </ol>
    </div>
  </div>

</div>

app/views/request/create.html.erb
<h1>Request#create</h1>
<p>Find me in app/views/request/create.html.erb</p>

app/views/shared/_navbar.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a href="/home" class="navbar-brand fw-bold">Real-time Search</a>
    <div class="d-flex " role="search">
      <a href="/userdashboard" class="btn btn-outline-primary mx-2">Your Analytics</a>
      <a href="/globaldashboard" class="btn btn-outline-success mx-2">Global Analytics</a href="/userdashboard">
    </div>
  </div>
</nav>